baseURL = "https://coding.observer"
languageCode = "en-us"
title = "Coding.Observer"
theme = "noteworthy"
enableRobotsTXT = false
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.
#test
# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = "" 

# Add your Disqus shortname here.
disqusShortname = ""    

[taxonomies]
  tag = "tags"

[author]
	name = "Johannes"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Personal blog about coding, tech and misc"
  title = "Coding Observer Blog"

  showReadMore = true

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
  enableKofi = true
  kofi = "I2I12FSW2"

    #Set FontAweome and enter your Kit ID
  enableFontAwesome = true
  fontawesome = "0dcacf6ba0"

  talkyardServerUrl = "https://comments-for-coding-observer.talkyard.net"
  talkyardScriptUrl = "https://c1.ty-cdn.net/-/talkyard-comments.min.js"


	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "#"
    twitter = "#"
    github = "#"
	stackoverflow = "#"

# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	weight = 1 

[[menu.main]]
	identifier = "about"
	name = "About me"
	url = "/about/"
	weight = 2 

[[menu.main]]
	identifier = "archives"
	name = "Archives"
	url = "/archives/"
	weight = 3

[[menu.main]]
	identifier = "Legal"
	name = "Legal"
	url = "/legal/"
	weight = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false

  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
